# Name: simple_arch
# Description: Describes an architecture composed by:
#  - 1 tile with: 
#     - 1 core (1 thread)
#     - 16 l2 slices
#  - 1 MCPU with: 
#     - 1 MC
#     - 8 memory banks 
#  - a functional NoC

---

# Simulation configuration
meta:
  params:
    architecture:  memory_controller_unit_test                    # (std::string)     Topology to simulate (tiled, l2_unit_test, memory_controller_unit_test)
    simulation_mode: trace_driven       # (std::string)     The type of simulation to perform (execution_driven, trace_driven). Mode execution_driven only supported for a tiled architecture
    show_factories: false                   # (bool)            Print generated factories
    trace: true                            # (bool)            Generate a trace into paraver format
    events_to_trace: [any]                  # (std::vector<std::string>)    The events to trace (comma-separated). Default: All of them
    cmd: apps/mt-matmul/matmul              # (std::string)     App to execute in the RISC-V simulator (Either a binary or trace depending on param simulation_mode)

# Architecture configuration
top:
  arch:
    memory_controller:
      params:
        num_banks: 32                       # (uint64_t)        The number of memory banks handled by this MC
        num_banks_per_group: 4              # (uint64_t)        The number of memory banks per bank group
        write_allocate: true                # (bool)            The write allocation policy
        request_reordering_policy: fifo      # (std::string)     The reordering policy for memory requests (fifo, access_type)
        command_reordering_policy: fifo     # (std::string)     The reordering policy for memory commands (fifo, oldest_ready)
        address_policy: row_bank_column_bank_group_interleave 
                                            # (std::string)     The data mapping molicy in main memory (open_page, close_page, row_bank_column_bank_group_interleave, row_column_bank, bank_row_column)

        unused_lsbs: 6                      # (uint8_t)         The number of bits that are unused in the address calculation
        unit_test: true
        mem_spec:                           # (vector<string>)  The memory latencies
          - "CCDL:3"
          - "CCDS:2"
          - "CKE:8"
          - "QSCK:1"
          - "FAW:16"
          - "PL:0"
          - "RAS:28"
          - "RC:42"
          - "RCDRD:12"
          - "RCDWR:6"
          - "REFI:3900"
          - "REFISB:244"
          - "RFC:220"
          - "RFCSB:96"
          - "RL:17"
          - "RP:14"
          - "RRDL:6"
          - "RRDS:4"
          - "RREFD:8"
          - "RTP:5"
          - "RTW:18"
          - "WL:7"
          - "WR:14"
          - "WTRL:9"
          - "WTRS:4"
          - "XP:8"
          - "XS:216"

      memory_bank*:
        params:
          num_rows: 16384                   # (uint64_t)        The number of rows
          num_columns: 64                   # (uint64_t)        The number of columns
          column_element_size: 32           # (uint64_t)        The size of column elements
          burst_length: 2                   # (uint8_t)         The number of columns handled back to back as a result of a READ/WRITE
